## Amount of Cargo machines per chunk (25 by default)
amount: 25

## Auto updater (true by default)
auto-update: true

## Size of the thread pool (4 by default)
## Only touch this setting when you know what you are doing!
thread-pool-size: 4

## Permissions (false by default)
## Permission node: headlimiter.permission.<name>
## Example: headlimiter.permission.noob
##
## When permissions have been set to true, you can use the values here to set the amount of heads checked.
## You can add as many entries as you want.
## Order has to be reversed or breaky breaky
permissions: false
permission:
  ## sefi: 25
  ## walshy: 20
  ## alessio: 15
  ## jeff: 10
  noob: 5